require conf/machine/raspberrypi4-64.conf

ENABLE_UART = "1"
SERIAL_CONSOLES = "115200;ttyS0"
RPI_EXTRA_CONFIG += "dtparam=uart0_console"

ENABLE_I2C = "1"
ENABLE_SPI = "1"

# eth0 via USB-Ethernet on RPi4 (smsc95xx)
KERNEL_MODULE_AUTOLOAD:append = " smsc95xx"

LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

BB_NUMBER_THREADS ?= "2"
PARALLEL_MAKE ?= "-j 2"
