require conf/distro/poky.conf

DISTRO = "roix"
DISTRO_NAME = "Roy Linux"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "scarthgap"

INIT_MANAGER = "systemd"

# Distro features — lean set for a headless RPi4
DISTRO_FEATURES = "acl argp bluetooth ext2 ipv4 ipv6 \
                   largefile pam seccomp systemd \
                   usbhost wifi xattr zeroconf"

DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
VIRTUAL-RUNTIME_login_manager = "shadow-base"

PREFERRED_PROVIDER_virtual/kernel = "linux-raspberrypi"

IMAGE_LINGUAS = "en-us"

DISTRO_EXTRA_RDEPENDS += ""
DISTRO_EXTRA_RRECOMMENDS += ""
